### ISSUE TITLE
Missing timestamps from GetMatchedOrders

### ISSUE THREAD

**Issue by diegofrata** [Fairlay/FairlayPrivateAPI#3]
Is it possible to include the timestamp when a bet was matched? This is available on the website but not on the API and it makes very difficult to do proper book keeping.

**Comment by Fairlay** [comment]
The OrderID is the timestamp!

Best,

Team Fairlay

------- Original Message -------
Diego Frata ***@***.***> schrieb am Freitag, 4. November 2022 um 19:09:

**Comment by diegofrata** [comment]
Thanks! Managed to use it. I don't think this is documented anywhere though, at least, I haven't seen it.
